### ISSUE TITLE
`build-args` does not accept multiple args

### ISSUE THREAD

**Issue by Seasawher** [leanprover/lean-action#108]
**Describe the bug**

Multiple args for `build-args` cases an error. for example:

```yml
      - name: lean action
        uses: leanprover/lean-action@v1
        with:
          build-args: "--log-level=warning --fail-level=warning"
```

**Expected behavior**
does not cause an error

**Link to workflow where bug was encountered:** [[link]](https://github.com/lean-ja/lean-by-example/actions/runs/11802866266/job/32879497747?pr=1089)

**Details**
 - `lean-action` version: v1
 - GitHub runner: `ubuntu-latest`
