### ISSUE TITLE
Configurations `build: false` and `test: false` Ignored in CI

### ISSUE THREAD

**Issue by abdoo8080** [leanprover/lean-action#110]
**Describe the bug**
Configurations `build: false` and `test: false` are ignored when running CI.

**Expected behavior**
The Lean action should not run the `lake build` and `lake test` commands.

**Link to workflow where bug was encountered:** [here](https://github.com/ufmg-smite/lean-smt/blob/7c0624781389fbefdf1f6c39105b1de0a07733d0/.github/workflows/ci.yml)

**Details**
- `lean-action` version: v1
- GitHub runner: `ubuntu-latest`, `macos-latest`, and `macos-13`
- Output:
  ```
  Run leanprover/lean-action@v1
    with:
      build: false
      test: false
      use-github-cache: false
      auto-config: true
      lint: default
      use-mathlib-cache: auto
      check-reservoir-eligibility: false
      lean4checker: false
      lake-package-directory: .
  Run : Install Elan
  Elan Installation Output
  
  Run : Configure Lean Action
  Configure lean-action
  Run : Detect Mathlib
  Detect Mathlib Output
  
  Run : Get Mathlib Cache
  Mathlib Cache
  
  Run : Lake Build
  Lake Build Output
  
  Run : Lake Test
  Lake Test Output
  ```

**Additional context**
I am setting these configurations to false while waiting for #108, which requests for multiple arguments to be passed to the `lake build` command.

**Comment by austinletson** [comment]
Thank you for the bug report.

I have identified the root cause here. I will release a fix for this bug along with the multiple `lake build` arguments in the next couple of days.

Until then, adding `auto-config: false` to your lean-action configuration should serve as a temporary fix. For example:

```yaml
- name: Configure lean-smt
      uses: leanprover/lean-action@v1
      with:
        auto-config: "false"
        build: "false"
        test: "false"
        use-github-cache: "false"
```
