### ISSUE TITLE
expose sub-jobs of the main action

### ISSUE THREAD

**Issue by b-mehta** [leanprover/lean-action#124]
In some of my projects, I'd like to only install elan, or only install elan and get cache, without wanting to do any of the (potentially slow) later steps. For instance, if I have a multi-job flow which can run on different setups, the first one needs elan and mathlib cache, can build the oleans for the project, and the next job doesn't need to (slowly) get the cache again. As such, it would be helpful if this action gave me either
a) the option to control which setup / cooldown parts run
b) sub-actions (like the cache action does) which let me do only parts of it

**Comment by austinletson** [comment]
Thank you for submitting an issue.

You can configure `lean-action` to only run certain sub-jobs using the action inputs. There are some examples in the [Configuring which features lean-action runs](https://github.com/leanprover/lean-action?tab=readme-ov-file#configuring-which-features-lean-action-runs) section of the README.

Setting `auto-config: False` is the key here because this will keep `lean-action` from trying to guess which sub-jobs to run based on the lakefile. See the [Breaking up lean-action across workflows](https://github.com/leanprover/lean-action?tab=readme-ov-file#breaking-up-lean-action-across-workflows) for details on `auto-config`.

Here is an example which only sets up `elan`:

```yml
- name: "use lean-action to set up elan"
  id: lean-action
  uses: leanprover/lean-action@v1
  with:
    auto-config: false # don't automatically run lake build, lake test, lake lint
    use-mathlib-cache: false # don't get the Mathlib cache
```

Does this help with your use case?
