### ISSUE TITLE
Inconsistency with `mathlib-cache` input

### ISSUE THREAD

**Issue by oliver-butterley** [leanprover/lean-action#25]
The current situation is:

```yml
mathlib-cache:
    description: |
      Run "lake exe cache get" before build.
      Project must be downstream of Mathlib.
      Allowed values: "true" or "false".
      If mathlib-cache input is not provided, the action will attempt to automatically detect if the project is downstream of Mathlib.
    required: false
    default: ""
```

```yml
    - name: detect mathlib
      # only detect Mathlib if the user did not provide the mathlib-cache input
      if: ${{ inputs.mathlib-cache == '' }}
      # etc...
```

An input here of either "true" or "false" will have the same effect. Possible solutions:
- the description of the input is changed,
- or, set `required: true` and `default: false` for this input and change the conditional to ${{ inputs.mathlib-cache == 'false' }}

Style note: could be clearer for the input name to be "get-mathlib-cache" or "use-mathlib-cache". (At the moment "mathlib-cache: true" could be understood to mean that the action can expect mathlib-cache to have already been obtained in a step prior to `lean-action`.)
