### ISSUE TITLE
v1-beta release

### ISSUE THREAD

**Issue by austinletson** [leanprover/lean-action#37]
- [x] Create a `release/v1-beta` branch for the release candidate.
- [x] Run  `functional_tests.yml` workflow on `release/v1-beta`.
- [x] Test `release/v1-beta` on existing test projects.
- [x] Create a release of `release/v1-beta` with a `v1-beta` tag. 
    - [x] Copy the release notes from the `## Unreleased` section of `CHANGELOG.md`.
- [x] Verify action with `uses: leanprover/lean-action@v1-beta`.
- [x] Create a PR to update `README.md` and `CHANGELOG.md`.

**Comment by austinletson** [comment]
# Functional tests for release/v1-beta
Several of the functional tests run for `lean-action@release/v1-alpha` are now covered by the `functional_tests.yml` workflow. [Here](https://github.com/leanprover/lean-action/actions/runs/9174218583) are the results of a successful run of `functional_tests.yml` on `lean-action@release/v1-beta`.

I have run the remaining tests manually using updated test repos.
## [use-lean-standard-action-with-bare-project](https://github.com/austinletson/use-lean-standard-action-with-bare-project)
simple lean package with v4.8.0-rc1
### test case 1: happy build
Covered by `functional_test.yml` workflow

### test case 2: build fails due to syntax error
Introduce an obvious lean syntax error to test the case where the build will fail
`lean-action` config is same as above.

#### Results
- [build link](https://github.com/austinletson/use-lean-standard-action-with-bare-project/actions/runs/9174352278/job/25225033995)
- build failed due to syntax error
### test case 3: lean4checker and reservoir eligibility
The use-lean-standard-action-with-bare-project should be eligible for reservoir because it is public, has an OSI approved license, and has 2 stars.

#### `lean-action` config
```yaml
- uses: leanprover/lean-action@release/v1-beta
  with:
    test: false
    lean4checker: true
    check-reservoir-eligibility: true
```

#### Results
- [build link](https://github.com/austinletson/use-lean-standard-action-with-bare-project/actions/runs/9174718582/job/25226160771)
- build ran successfully
- lean4checker ran successfully
- reservoir eligibility detected successfully 

### test case 4: run `lake build` with `--quiet` option
#### `lean-action` config
```yaml
- uses: leanprover/lean-action@release/v1-beta
  with:
    test: false
    build-args: "--quiet"
```
#### Results
- [build link](https://github.com/austinletson/use-lean-standard-action-with-bare-project/actions/runs/9175005591/job/25227057454)
- `lake build --quiet` ran successfully
## [use-lean-action-with-toml-lake-file](https://github.com/austinletson/use-lean-action-with-toml-lake-file)
lean package downstream of `mathlib` which uses `lakefile.toml`
### test case 1: lint-module, check-reservoir-eligibility
#### `lean-action` config
```yaml
- uses: leanprover/lean-action@release/v1-beta
  with:
    test: false 
    lint-module: "UseLeanActionWithTomlLakeFile"
    check-reservoir-eligibility: true
```
#### Results
- [build link](https://github.com/austinletson/use-lean-action-with-toml-lake-file/actions/runs/9174985233/job/25226990768)
- `mathlib` dependency was successfully detected and `lake exe cache get` was run
- build succeeded
- lint succeeded
- reservoir check failed because no SPDX license and repo as less than 2 stars

## [use-lean-standard-action-with-lake-test](https://github.com/austinletson/use-lean-standard-action-with-lake-test)
lean package with v4.8.0-rc1 with a `@[test_runner]` entry point in lakefile.lean
### test case 1: fake tests pass
Covered by `functional_test.yml` workflow

### test case 2: fake tests fail
`@[test_runner]` entry point returns `1` exit status

#### `lean-action` config
```yaml
- uses: leanprover/lean-action@release/v1-alpha
  with:
    test: true
```
#### Results
- [build link](https://github.com/austinletson/use-lean-standard-action-with-lake-test/actions/runs/9174537275/job/25225604772)
- build succeeded
- fake tests failed
