### ISSUE TITLE
Automatically check if test runner is available

### ISSUE THREAD

**Issue by Seasawher** [leanprover/lean-action#53]
Automatically checks if `test_driver` or `test_runner` is defined in `lakefile.lean` and executes `lake test` if it is defined, otherwise does not.

It would be tedious to have the user manually enter whether or not to run `lake test` each time. default input should be `auto`.

**Comment by austinletson** [comment]
I think this is the right approach. What do you think about resolving this issue as well as #30 and #46 by introducing improved unified semantics for how users enable the `lake build`, `lake test`, and `lake lint` steps?

**Comment by austinletson** [comment]
Digging into the details a little more:

As an alternative to having `test: auto` and `lint: auto`, we could introduce a boolean `auto_config` parameter that indicates `lean-action` should try to determine which steps to run automatically. For now, this would be `lake build` plus use `lake check-test` and `lake check-lint` to determine `lake test` and `lake lint`. This input would provide more flexibility for delivering the best default experience as the Lean ecosystem develops and allow users to turn off automatic configuration entirely for more specific use cases, e.g., cron job workflows.
 
 For example, `lake init` could initialize `lean-action` as:
```yaml
- uses: leanprover/lean-action
  with:
    auto_config: true
```

Users could optionally override the behavior for specific steps while still taking advantage of the automatic configuration: 
```yaml
- uses: leanprover/lean-action
  with:
    auto_config: true
    test: false
    check-reservoir-eligibility: true
```

Or if they have a specific need in their workflow, such as just running `lean4checker` in a cron job, they could start from scratch:
```yaml
- uses: leanprover/lean-action
  with:
    auto-config: false
    lean4checker: true
```

We could make `auto-config: true` the default, so 'auto-config' could be omitted in the first two examples above.

What are your thoughts @seasawher?
