### ISSUE TITLE
Problem about caching strategy for Lean

### ISSUE THREAD

**Issue by SnO2WMaN** [leanprover/lean-action#64]
**Note: This is based on my assumptions and might not be entirely accurate.**

This issue occurs when we update our project from `v4.9.0-rc1` to `v4.9.0-rc2`. https://github.com/iehality/lean4-logic/pull/85
And it seems to be happens same problem branch in the [nightly branch of the import-graph](https://github.com/leanprover-community/import-graph/tree/nightly-testing).

In our project, we set the GitHub Action cache strategy as follows
```yaml
path: .lake
key: lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}-${{ github.ref }}
restore-keys: |
    lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}-${{ github.ref }}
    lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}
    lake-${{ runner.os }}
```

The problem we encountered was with the `restore-keys` we specified. The issue is that when updating the Lean version itself, the previous version's cache also becomes a fallback candidate. In our project, it seems we referenced the v4.9.0-rc1 cache, which caused the build to fail.

Solution is remove fallbacks of `restore-keys` to `lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}-${{ github.ref }}` only.

Currently, the cache strategy of this action is similar (i.e., it doesn't avoid using the cache when the Lean version itself is updated). 

https://github.com/leanprover/lean-action/blob/52906d40616a3ed5a566f5f01db39858c0f6eee2/action.yml#L93-L99

This seems to be why the nightly branch of the import-graph is broken.
As a solution, specifying `${{ hashFiles('lean-toolchain') }}` as the key should work.
